projeto/mercado/mercado/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path("produtos/", include('produtos.urls')),
    path("", views.principal, name='principal')
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/mercado/produtos/urls.py
from django.urls import path
from . import views

app_name = 'produtos'
urlpatterns = [

    path("", views.tela_principal, name='tela_produtos'),

]

projeto/mercado/usuarios/urls.py
from django.urls import path, include
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login, name='login'),
    path("vendedores/", views.tela_vendedores, name='vendedores'),
    path('detalhes/', views.detalhes, name='detalhes'),
    path('remover/<int:id>', views.tela_remover, name='remover'),
    path('editar/<int:id>', views.tela_editar, name='editar'),
    path('autenticado/', views.autenticado, name='autenticado'),
    path('cadastrado/', views.cadastrado, name='cadastrado')
]

projeto/mercado/produtos/models.py
from django.db import models

# Create your models here.

projeto/mercado/usuarios/models.py
from django.db import models

class Produtos(models.Model):
    nome = models.CharField(max_length=45)
    perecivel = models.BooleanField(default=False)
    preco = models.FloatField()
    marca = models.CharField(max_length=25)
    imagem = models.ImageField(upload_to='produtos/', null=True, blank=True)
    
    def __str__(self):
        return self.nome
    

projeto/mercado/usuarios/forms.py
from django import forms
from .models import Produtos
from django.contrib.auth.models import User

class ProdutoForms(forms.ModelForm):
    class Meta:
        model = Produtos
        fields = ['nome', 'perecivel', 'preco', 'marca', 'imagem']
        

projeto/mercado/mercado/views.py
from django.shortcuts import render

def principal(request):
    return render(request, 'principal/principal.html',)

projeto/mercado/produtos/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from usuarios.models import Produtos
from usuarios.forms import ProdutoForms


# Create your views here.
def tela_principal(request):
    contexto = {
        'produtos': Produtos.objects.all()
        
        
    }
    return render(request, 'produtos/tela_produtos.html', contexto)

projeto/mercado/usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.http import HttpRequest
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth.decorators import login_required
from .forms import ProdutoForms
from usuarios.models import Produtos


# Create your views here.
def cadastro(request:HttpRequest):
    if request.method == "GET":
        return render(request, 'usuarios/cadastro.html')
    else:
        username = request.POST.get("username")
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        user = User.objects.filter(username=username).first()
        if user:
            return HttpResponse("Já existem um usruario com este nome!")
        
        user = User.objects.create_user(username=username, email=email, password=senha)
        user.save()

        return render(request, 'usuarios/cadastrado.html')
    

def login(request):
    if request.method == "GET":
        return render(request, "usuarios/login.html")
    else:
        username = request.POST.get('username')
        senha = request.POST.get('senha')

        user = authenticate(username=username, password=senha)

        if user:
            login_django(request, user)
            return render(request, 'usuarios/autenticado.html')
        else:
            return HttpResponse("Usuario ou senha inválidos")
    

@login_required(login_url='/auth/login/')
def tela_vendedores(request:HttpRequest):
    if request.method == "POST":
        file = request.FILES.get('imagem')
        formulario = ProdutoForms(request.POST, request.FILES)
        if formulario.is_valid():
            formulario.save()

            return redirect('produtos:tela_produtos')
        
    contexto ={
        
        'form':ProdutoForms
    }

    
    return render(request, 'usuarios/tela_vendedores.html', contexto)


@login_required(login_url='/auth/login/')
def detalhes(request:HttpRequest):
    contexto = {
        'produtos':Produtos.objects.all()
    }
    return render(request, 'usuarios/detalhes.html', contexto)

@login_required(login_url='/auth/login/')
def tela_remover(request:HttpRequest, id):
    produto = get_object_or_404(Produtos,id=id)
    produto.delete()
    return render(request, 'usuarios/remover_produtos.html')


@login_required(login_url='/auth/login/')
def tela_editar(request:HttpRequest, id):
    produto = get_object_or_404(Produtos, id=id)
    if request.method == "POST":
        formulario = ProdutoForms(request.POST, instance=produto)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuarios:detalhes')
    
    formulario = ProdutoForms(instance=produto)
    contexto = {
        'form': formulario
    }
    return render(request, 'usuarios/editar.html', contexto)

def autenticado(request):
    return render(request, 'usuarios/autenticado.html')

def cadastrado(request):
    return render(request, 'usuarios/cadastrado.html')

projeto/mercado/usuarios/templates/principal/principal.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LM</title>
    <style>

body{
    margin: 0px;
    background-color: rgb(255, 255, 255);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    
}

header a{
    color: aliceblue;
    text-decoration: none;
    margin: 70px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;}



header{
    color: white;
    background-color: orange;
    text-align: center;
    padding: 30px;
    font-family: Georgia, 'Times New Roman', Times, serif;}


header a:hover{
    color: red;
    text-decoration: underline;}

nav{
        background-color: rgb(255, 102, 0);
        padding: 20px;
        text-align: center;
    }
nav a {
    color: white;
    margin-right: 20px;
    font-size: 20px;
    text-decoration: none;
}
nav a:hover {
    text-decoration: underline;
    transition: color 0.5s;
    color: rgb(0, 0, 0);
}


h3{
    text-align: center;
    font-size: 24px;
}


h2{
    text-align: center;
}
header img{
    margin-left: 1700px;
}
main{
    background-color: rgb(255, 255, 255);
    padding: 10px;
    width: 500px;
    margin: auto;
    border: gray solid 1px;
}

footer{
        background-color: orangered;
        color: white;
        padding: 10px;
        text-align: center;}


#logo{
    display: inline;
    
}

    </style>
</head>
<body>
    <header>
        <a href="{% url 'usuarios:login' %}">
             <img src="{% static 'img/user.png' %}" alt="user" width="30px">
             
        </a>
         <h1 id="logo">Supermercado</h1>
         <h1>LM</h1>
 
     </header>
     <nav>
         <a href="{% url 'principal' %}">Principal</a>
         <a href="{% url 'usuarios:detalhes' %}">Detalhes</a>
 
     </nav>
    <main>
        

        <section id="sobre">
            <h2>Sobre Nós</h2>
            Bem-vindo ao <strong>LM</strong>!

            <p>Somos mais do que um supermercado — somos parte da sua rotina, da sua família e da sua comunidade. Desde nossa fundação, temos o compromisso de oferecer produtos de qualidade, atendimento acolhedor e preços justos para tornar o seu dia a dia mais prático e acessível.</p>

            <p>Aqui, você encontra uma ampla variedade de alimentos frescos, produtos de higiene, limpeza, bebidas, itens para o lar e muito mais. Trabalhamos com as melhores marcas do mercado e também valorizamos os produtores locais, garantindo variedade, frescor e procedência.</p>

            <p>Nosso time está sempre pronto para te atender com simpatia e dedicação. Queremos que cada visita ao <strong>LM</strong> seja física ou online, se torne uma experiência positiva, segura e agradável.</p>

            <p>Acreditamos na força da vizinhança, por isso investimos em ações sociais e sustentáveis, apoiando projetos locais e promovendo o consumo consciente.</p>

            <p>Obrigado por confiar no <strong>LM</strong>. Estamos aqui por você e para você, todos os dias.</p>


        </section>

    </main>

    <footer>
        <p>Site desenvolvido por Lucas Eduardo, em estudo do Curso de Tecnico em Desenvolvimento de Sistema - SENAC</p>
    </footer>
    
</body>
</html>

projeto/mercado/usuarios/templates/produtos/tela_produtos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Produtos</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <style>
            
.produtos {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    grid-template-rows: repeat(5, 1fr);
    gap: 6px;
    background-color: rgb(255, 255, 255);
    padding: 20px;
}
    
.produto {
    grid-row: span 2 / span 2;
    width: 350px;
    height: 400px;
    padding: 10px;
    border: 2px solid rgb(143, 142, 142);
    border-radius: 5px;
    background-color: rgb(255, 255, 255);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    padding-bottom: 50px;
    text-align: center;

}
.produto a {
    color: rgb(162, 16, 16);
    
}
.produto a:hover{
    text-decoration: underline;
    color: blue;
}
.produto img {
    width: 300px;
    height: 200px;
    
    border-radius: 5px;
    margin-bottom: 10px;
}

.formulario{
    background-color: white;
    margin: auto;
    text-align: center;
    padding: 10px;
    width: 300px;
    height: 400px;
    margin-top: 30px;
    border-radius: 5px;
    box-shadow: 3px 3px 3px gray;
    margin-bottom: 200px;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;

}
.aviso{
    background-color: rgb(128, 31, 31);
    padding: 60px;
    text-align: center;
    color: wheat;
}

#novo_produto{
    margin: center;
    padding: 10px;
    background-color: white;
    border-radius: 10px;
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
    
    
}

input{
    padding: 6px;
    margin-bottom: 10px;
    background-color: rgb(222, 218, 218);
}

body{
    margin: 0px;
    background-color: rgb(199, 199, 199);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    
}

header a{
    color: aliceblue;
    text-decoration: none;
    margin: 70px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;}



header{
    color: white;
    background-color: orange;
    text-align: center;
    padding: 30px;
    font-family: Georgia, 'Times New Roman', Times, serif;}


header a:hover{
    color: red;
    text-decoration: underline;}

nav{
        background-color: rgb(255, 102, 0);
        padding: 20px;
        text-align: center;
    }
nav a {
    color: white;
    margin-right: 20px;
    font-size: 20px;
    text-decoration: none;
}
nav a:hover {
    text-decoration: underline;
    transition: color 0.5s;
    color: rgb(0, 0, 0);
}


h3{
    text-align: center;
    font-size: 24px;
}


h2{
    text-align: center;
}
header img, p{
    margin-left: 1700px;
}

footer{
        background-color: orangered;
        color: white;
        padding: 10px;
        text-align: center;}

    </style>
</head>
<body>
    <header>
       <a href="{% url 'usuarios:login' %}">
            <img src="{% static 'img/user.png' %}" alt="user" width="30px">
            <p>Login</p>
       </a>
        <h1>Supermercado LM</h1>

    </header>
    <nav>
        <a href="{% url 'principal' %}">Principal</a>
        <a href="{% url 'usuarios:detalhes' %}">Detalhes</a>

    </nav>


    
    <div class="produtos">
        {% for produto in produtos %}
        <div class="produto">
            
            {% if produto.imagem %}
                <img src="{{ produto.imagem.url }}" alt="produto imagem" width="200px">
            {% else %}
                <p>Sem imagem</p>  {# ou coloque uma imagem padrão se quiser #}
            {% endif %}
            <hr>
            <div id="titulo">
                <h3>{{produto.nome}}</h3>
            </div>

            <p>{% if produto.completo %} Não Perecível{% else %} Perecível {% endif %}</p>
            <p>{{produto.marca}}</p>
            <p>R$ {{produto.preco}}</p>
        </div>
        {% endfor %}
    </div>

    <footer>
        <p>Site desenvolvido por Lucas Eduardo, em estudo do Curso de Tecnico em Desenvolvimento de Sistema - SENAC</p>
    </footer>
   
</body>
</html>

projeto/mercado/usuarios/templates/usuarios/autenticado.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autenticado!</title>
    <style>
        #autenticado{
            background-color: rgb(247, 131, 55);
            color: rgb(255, 255, 255);
            width: 300px;
            height: 400px;
            margin: auto;
            text-align: center;
            padding: 10px;
            border-radius: 5px;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
           
        }
        h3{
            margin-top: 30px;
            margin-bottom: 50px;
        }
        p{
            padding-bottom: 30px;
        }
    </style>
</head>
<body>

    <div id="autenticado">
        <h3>Você foi autenticado com sucesso!</h3>

        <p>Agora com o seu Login,você pode entrar na sua conta e aproveitar as suas novas opções😊, como adicionar novos produtos, editar e excluir produtos existentes.</p>
        <a href="{% url 'usuarios:detalhes' %}">Editar produtos</a>
        <br>
        <a href="{% url 'usuarios:vendedores' %}">Criar  produtos</a>
    </div>


    
</body>
</html>

projeto/mercado/usuarios/templates/usuarios/cadastrado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>

        #cadastrado{
            background-color: gray;
            color: white;
            border-radius: 4px;
            padding: 20px;
            width: 500px;
            height: 300px;
            text-align: center;
            
        }
        h3{
            margin-bottom: 70px;
        }
        a{
            text-decoration: none;
            color: orange;
        }
        a:hover{
            text-decoration: underline;
            color: red;
        }
    </style>
</head>
<body>
    <div id="cadastrado">
        <h3>Cadastrado Com sucesso!😊</h3>
        <p>Faça seu Login agora:</p>
        <br>
        <a href="{% url 'usuarios:login' %}">Login</a>
    </div>
    
</body>
</html>

projeto/mercado/usuarios/templates/usuarios/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Vendedor</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
    <header>
       <a href="{% url 'usuarios:login' %}">
            <img src="{% static 'img/user.png' %}" alt="user" width="30px">
       </a>
        <h1>Supermercado LM</h1>

    </header>
    <nav>
        <a href="{% url 'principal' %}">Principal</a>
        <a href="{% url 'usuarios:detalhes' %}">Detalhes</a>

    </nav>  
    <body>
        
        <form action="{% url 'usuarios:cadastro' %}" method="POST" class="formulario">{% csrf_token %}
            <h3>CADASTRAR</h3>
            <input type="text" name="username" id="username" placeholder="Usuário">
            <br>
            <input type="text" name="email" id="email" placeholder="email">
            <br>
            <input type="password" name="senha" id="senha" placeholder="senha">
            <br>
            <input type="submit" value="Cadastrar">
            <br><br>
            <a href="{% url 'usuarios:login' %}">Fazer Login</a>
            <a href="{% url 'produtos:tela_produtos' %}">Voltar</a>
        </form>
         
    </body>
    <footer>
        <p>Site desenvolvido por Lucas Eduardo, em estudo do Curso de Tecnico em Desenvolvimento de Sistema - SENAC</p>
    </footer>
</html>

projeto/mercado/usuarios/templates/usuarios/detalhes.html
{% load static  %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
            
        .produtos {
            display: grid;
            grid-template-columns: repeat(5, 1fr);
            grid-template-rows: repeat(5, 1fr);
            gap: 5px;
            background-color: rgb(255, 255, 255);
            padding: 20px;
        }
        
            
        .produto {
            grid-row: span 2 / span 2;
            width: 350px;
            height: 400px;
            padding: 10px;
            border: 2px solid rgb(95, 94, 94);
            border-radius: 5px;
            background-color: white;
            font-family: 'Segoe UI', Tahoma, Verdana, sans-serif;
            padding-bottom: 50px;
            text-align: center;
        
        }
        .produto a {
            color: rgb(162, 16, 16);
            
        }
        .produto a:hover{
            text-decoration: underline;
            color: blue;
        }
        .produto img {
            width: 300px;
            height: 200px;
            object-fit: cover;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        
        .formulario{
            background-color: white;
            margin: auto;
            text-align: center;
            padding: 10px;
            width: 300px;
            height: 400px;
            margin-top: 30px;
            border-radius: 5px;
            box-shadow: 3px 3px 3px gray;
            margin-bottom: 200px;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        
        }
        .aviso{
            background-color: rgb(128, 31, 31);
            padding: 60px;
            text-align: center;
            color: wheat;
        }
        
        #novo_produto{
            margin: center;
            padding: 10px;
            background-color: white;
            border-radius: 10px;
            text-align: center;
            font-family: Arial, Helvetica, sans-serif;
            
            
        }
        
        input{
            padding: 6px;
            margin-bottom: 10px;
            background-color: rgb(222, 218, 218);
        }
        
        body{
            margin: 0px;
            background-color: rgb(199, 199, 199);
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            
        }
        
        header a{
            color: aliceblue;
            text-decoration: none;
            margin: 70px;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;}
        
        
        
        header{
            color: white;
            background-color: orange;
            text-align: center;
            padding: 30px;
            font-family: Georgia, 'Times New Roman', Times, serif;}
        
        
        header a:hover{
            color: red;
            text-decoration: underline;}
        
        h3{
            text-align: center;
            font-size: 24px;
        }
        
        
        h2{
            text-align: center;
        }
        
        footer{
                background-color: orangered;
                color: white;
                padding: 10px;
                text-align: center;}
        
        
        
            </style>
    
</head>
<body>
    <header>

        <h1>Supermercado LM</h1>

        <a href="{% url 'principal' %}">Principal</a>
        <a href=" {% url 'produtos:tela_produtos' %}">Produtos</a>
    </header>

    <div class="aviso">
        <p>Esta área é exclusiva para vendedores que possuem login, onde se pode editar e adicionar novos produtos.</p>
    </div>
   
<div class="produtos">

    {% for produto in produtos %}

    <div class="produto">
        <h3>{{produto.nome}}</h3>
        {% if produto.imagem %}
                <img src="{{ produto.imagem.url }}" alt="produto imagem" width="200px">
            {% else %}
                <p>Sem imagem</p>  {# ou coloque uma imagem padrão se quiser #}
            {% endif %}
        <p>{{produto.marca}}</p>
        <p>R$ {{produto.preco}}</p>
        <a href="{% url 'usuarios:remover' produto.id %}">Remover</a>
        <a href="{% url 'usuarios:editar' produto.id %}">Editar</a>
    </div>
    {% endfor %}
    <div id="novo_produto">

        <a href="{% url 'usuarios:vendedores' %}"><img src="{% static 'img/add.png' %}" alt="adicionar_produto" width="200px"></a>
        <p>NOVO PRODUTO</p>
    </div>
</div>
<footer>
    <p>Site desenvolvido por Lucas Eduardo, em estudo do Curso de Tecnico em Desenvolvimento de Sistema - SENAC</p>
</footer>

</body>
</html>

projeto/mercado/usuarios/templates/usuarios/editar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Produtos</title>
</head>
<body>
    <h1>Aqui é somente para vendedores da loja, onde iremos adicionar produtos novos</h1>

    <form action="" method="post">
        <h3>Adicionar Produto</h3>

        {% csrf_token %}
        {{form}}

        <br>
    <input type="submit" value="Enviar">
    </form>

    <a href="#">Voltar para o início</a>
    <a href="#">Editar Produtos</a>
    
</body>
</html>

projeto/mercado/usuarios/templates/usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <h1>Supermercado LM</h1>
        
        <a href="{% url 'produtos:tela_produtos' %}">Produtos</a>
        <a href="{% url 'usuarios:login' %}">Login</a>
    </header>   
    
    <form action="" method="POST" class="formulario">{% csrf_token %}
        <h3>LOGIN</h3>
        <input type="text" name="username" id="username" placeholder="Usuário">
        <br>
        <input type="password" name="senha" id="senha" placeholder="senha">
        <br>
        <input type="submit" value="Logar">
        <br><br>
        <a href="{% url 'usuarios:cadastro' %}">Cadastrar</a>
        <a href="{% url 'produtos:tela_produtos' %}">Voltar</a>
    </form>
    
    <footer>
        <p>Site desenvolvido por Lucas Eduardo, em estudo do Curso de Tecnico em Desenvolvimento de Sistema - SENAC</p>
    </footer>
    
</body>
</html>

projeto/mercado/usuarios/templates/usuarios/remover_produtos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    <h1>Removido com sucesso</h1>

    <a href="{% url 'produtos:tela_produtos' %}">Voltar</a>
</body>
</html>

projeto/mercado/usuarios/templates/usuarios/tela_vendedores.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Produtos</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
       <a href="{% url 'usuarios:login' %}">
            <img src="{% static 'img/user.png' %}" alt="user" width="30px">
       </a>
        <h1>Supermercado LM</h1>

    </header>
    <nav>
        <a href="{% url 'principal' %}">Principal</a>
        <a href="{% url 'usuarios:detalhes' %}">Detalhes</a>

    </nav>
    
    <div class="aviso">
        <p>Esta área é exclusiva para vendedores que possuem login, onde se pode editar e adicionar novos produtos.</p>
    </div>

    <form action="" method="post" enctype="multipart/form-data" class="formulario">
        <h3>Adicionar Produto</h3>

        {% csrf_token %}
        {{form}}

        <br>
    <input type="submit" value="Enviar">
    <br>

    <a href="#">Voltar para o início</a>
    <a href="#">Editar Produtos</a>
    </form>

    <footer>
        <p>Site desenvolvido por Lucas Eduardo, em estudo do Curso de Tecnico em Desenvolvimento de Sistema - SENAC</p>
    </footer>
    
</body>
</html>